openapi: 3.2.0
info:
  version: 2017-09-30
  x-release: v4
  title: Amazon Kinesis Video Streams Describe Stream API
  description: <p/>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: kinesisvideo
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/kinesisvideo-2017-09-30.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://kinesisvideo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Kinesis Video multi-region endpoint
- url: https://kinesisvideo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Kinesis Video multi-region endpoint
- url: http://kinesisvideo.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Kinesis Video endpoint for China (Beijing) and China (Ningxia)
- url: https://kinesisvideo.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Kinesis Video endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: DescribeStream
paths:
  /describeStream:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeStream
      description: 'Returns the most current information about the specified stream. You must specify either the <code>StreamName</code> or the <code>StreamARN</code>. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeStreamOutput'
        '480':
          description: InvalidArgumentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArgumentException'
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '482':
          description: ClientLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientLimitExceededException'
        '483':
          description: NotAuthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotAuthorizedException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                StreamName:
                  description: The name of the stream.
                  type: string
                  pattern: '[a-zA-Z0-9_.-]+'
                  minLength: 1
                  maxLength: 256
                StreamARN:
                  description: The Amazon Resource Name (ARN) of the stream.
                  type: string
                  pattern: arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+
                  minLength: 1
                  maxLength: 1024
      tags:
      - DescribeStream
components:
  schemas:
    DataRetentionInHours:
      type: integer
      minimum: 0
    ResourceNotFoundException: {}
    DescribeStreamOutput:
      type: object
      properties:
        StreamInfo:
          allOf:
          - $ref: '#/components/schemas/StreamInfo'
          - description: An object that describes the stream.
    KmsKeyId:
      type: string
      pattern: .+
      minLength: 1
      maxLength: 2048
    StreamName:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 256
    Version:
      type: string
      pattern: '[a-zA-Z0-9]+'
      minLength: 1
      maxLength: 64
    ResourceARN:
      type: string
      pattern: arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+
      minLength: 1
      maxLength: 1024
    InvalidArgumentException: {}
    NotAuthorizedException: {}
    ClientLimitExceededException: {}
    Timestamp:
      type: string
      format: date-time
    StreamInfo:
      type: object
      properties:
        DeviceName:
          allOf:
          - $ref: '#/components/schemas/DeviceName'
          - description: The name of the device that is associated with the stream.
        StreamName:
          allOf:
          - $ref: '#/components/schemas/StreamName'
          - description: The name of the stream.
        StreamARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The Amazon Resource Name (ARN) of the stream.
        MediaType:
          allOf:
          - $ref: '#/components/schemas/MediaType'
          - description: 'The <code>MediaType</code> of the stream. '
        KmsKeyId:
          allOf:
          - $ref: '#/components/schemas/KmsKeyId'
          - description: The ID of the Key Management Service (KMS) key that Kinesis Video Streams uses to encrypt data on the stream.
        Version:
          allOf:
          - $ref: '#/components/schemas/Version'
          - description: The version of the stream.
        Status:
          allOf:
          - $ref: '#/components/schemas/Status'
          - description: The status of the stream.
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: A time stamp that indicates when the stream was created.
        DataRetentionInHours:
          allOf:
          - $ref: '#/components/schemas/DataRetentionInHours'
          - description: How long the stream retains data, in hours.
      description: An object describing a Kinesis video stream.
    Status:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
    MediaType:
      type: string
      pattern: '[\w\-\.\+]+/[\w\-\.\+]+(,[\w\-\.\+]+/[\w\-\.\+]+)*'
      minLength: 1
      maxLength: 128
    DeviceName:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 128
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/kinesisvideo/
