openapi: 3.0.0
info:
  version: 2015-08-04
  x-release: v4
  title: 'Amazon Kinesis Firehose CreateSignalingChannel #X Amz Target=KinesisAnalytics 20180523.AddApplicationOutput API'
  description: <fullname>Amazon Kinesis Data Firehose API Reference</fullname> <p>Amazon Kinesis Data Firehose is a fully managed service that delivers real-time streaming data to destinations such as Amazon Simple Storage Service (Amazon S3), Amazon OpenSearch Service, Amazon Redshift, Splunk, and various other supportd destinations.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: firehose
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/firehose-2015-08-04.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://firehose.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Firehose multi-region endpoint
- url: https://firehose.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Firehose multi-region endpoint
- url: http://firehose.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Firehose endpoint for China (Beijing) and China (Ningxia)
- url: https://firehose.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Firehose endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=KinesisAnalytics 20180523.AddApplicationOutput'
paths:
  /#X-Amz-Target=KinesisAnalytics_20180523.AddApplicationOutput:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: AddApplicationOutput
      description: <p>Adds an external destination to your SQL-based Kinesis Data Analytics application.</p> <p>If you want Kinesis Data Analytics to deliver data from an in-application stream within your application to an external destination (such as an Kinesis data stream, a Kinesis Data Firehose delivery stream, or an Amazon Lambda function), you add the relevant configuration to your application using this operation. You can configure one or more outputs for your application. Each output configuration maps an in-application stream and an external destination.</p> <p> You can use one of the output configurations to deliver data from your in-application error stream to an external destination so that you can analyze the errors. </p> <p> Any configuration update, including adding a streaming source using this operation, results in a new version of the application. You can use the <a>DescribeApplication</a> operation to find the current application version.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddApplicationOutputResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: ResourceInUseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceInUseException'
        '482':
          description: InvalidArgumentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArgumentException'
        '483':
          description: ConcurrentModificationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentModificationException'
        '484':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddApplicationOutputRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - KinesisAnalytics_20180523.AddApplicationOutput
      tags:
      - '#X Amz Target=KinesisAnalytics 20180523.AddApplicationOutput'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    KinesisFirehoseOutputDescription:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The Amazon Resource Name (ARN) of the delivery stream.
        RoleARN:
          allOf:
          - $ref: '#/components/schemas/RoleARN'
          - description: <p>The ARN of the IAM role that Kinesis Data Analytics can assume to access the stream.</p> <note> <p>Provided for backward compatibility. Applications that are created with the current API version have an application-level service execution role rather than a resource-level role.</p> </note>
      description: For a SQL-based Kinesis Data Analytics application's output, describes the Kinesis Data Firehose delivery stream that is configured as its destination.
    ApplicationName:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 128
    ApplicationVersionId:
      type: integer
      minimum: 1
      maximum: 999999999
    ResourceARN:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 2048
    LambdaOutput:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: '<p>The Amazon Resource Name (ARN) of the destination Lambda function to write to.</p> <note> <p>To specify an earlier version of the Lambda function than the latest, include the Lambda function version in the Lambda function ARN. For more information about Lambda ARNs, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda">Example ARNs: Amazon Lambda</a> </p> </note>'
      description: 'When you configure a SQL-based Kinesis Data Analytics application''s output, identifies an Amazon Lambda function as the destination. You provide the function Amazon Resource Name (ARN) of the Lambda function. '
    OutputDescription:
      type: object
      properties:
        OutputId:
          allOf:
          - $ref: '#/components/schemas/Id'
          - description: A unique identifier for the output configuration.
        Name:
          allOf:
          - $ref: '#/components/schemas/InAppStreamName'
          - description: The name of the in-application stream that is configured as output.
        KinesisStreamsOutputDescription:
          allOf:
          - $ref: '#/components/schemas/KinesisStreamsOutputDescription'
          - description: Describes the Kinesis data stream that is configured as the destination where output is written.
        KinesisFirehoseOutputDescription:
          allOf:
          - $ref: '#/components/schemas/KinesisFirehoseOutputDescription'
          - description: Describes the Kinesis Data Firehose delivery stream that is configured as the destination where output is written.
        LambdaOutputDescription:
          allOf:
          - $ref: '#/components/schemas/LambdaOutputDescription'
          - description: Describes the Lambda function that is configured as the destination where output is written.
        DestinationSchema:
          allOf:
          - $ref: '#/components/schemas/DestinationSchema'
          - description: The data format used for writing data to the destination.
      description: 'For a SQL-based Kinesis Data Analytics application, describes the application output configuration, which includes the in-application stream name and the destination where the stream data is written. The destination can be a Kinesis data stream or a Kinesis Data Firehose delivery stream. '
    LambdaOutputDescription:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The Amazon Resource Name (ARN) of the destination Lambda function.
        RoleARN:
          allOf:
          - $ref: '#/components/schemas/RoleARN'
          - description: <p>The ARN of the IAM role that Kinesis Data Analytics can assume to write to the destination function.</p> <note> <p>Provided for backward compatibility. Applications that are created with the current API version have an application-level service execution role rather than a resource-level role.</p> </note>
      description: 'For a SQL-based Kinesis Data Analytics application''s output, describes the Amazon Lambda function that is configured as its destination. '
    AddApplicationOutputRequest:
      type: object
      required:
      - ApplicationName
      - CurrentApplicationVersionId
      - Output
      title: AddApplicationOutputRequest
      properties:
        ApplicationName:
          allOf:
          - $ref: '#/components/schemas/ApplicationName'
          - description: The name of the application to which you want to add the output configuration.
        CurrentApplicationVersionId:
          allOf:
          - $ref: '#/components/schemas/ApplicationVersionId'
          - description: 'The version of the application to which you want to add the output configuration. You can use the <a>DescribeApplication</a> operation to get the current application version. If the version specified is not the current version, the <code>ConcurrentModificationException</code> is returned. '
        Output:
          allOf:
          - $ref: '#/components/schemas/Output'
          - description: An array of objects, each describing one output configuration. In the output configuration, you specify the name of an in-application stream, a destination (that is, a Kinesis data stream, a Kinesis Data Firehose delivery stream, or an Amazon Lambda function), and record the formation to use when writing to the destination.
    RoleARN:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 2048
    InvalidArgumentException: {}
    DestinationSchema:
      type: object
      required:
      - RecordFormatType
      properties:
        RecordFormatType:
          allOf:
          - $ref: '#/components/schemas/RecordFormatType'
          - description: Specifies the format of the records on the output stream.
      description: 'Describes the data format when records are written to the destination in a SQL-based Kinesis Data Analytics application. '
    ConcurrentModificationException: {}
    AddApplicationOutputResponse:
      type: object
      properties:
        ApplicationARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The application Amazon Resource Name (ARN).
        ApplicationVersionId:
          allOf:
          - $ref: '#/components/schemas/ApplicationVersionId'
          - description: The updated application version ID. Kinesis Data Analytics increments this ID when the application is updated.
        OutputDescriptions:
          allOf:
          - $ref: '#/components/schemas/OutputDescriptions'
          - description: 'Describes the application output configuration. For more information, see <a href="https://docs.aws.amazon.com/kinesisanalytics/latest/dev/how-it-works-output.html">Configuring Application Output</a>. '
    Output:
      type: object
      required:
      - Name
      - DestinationSchema
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/InAppStreamName'
          - description: The name of the in-application stream.
        KinesisStreamsOutput:
          allOf:
          - $ref: '#/components/schemas/KinesisStreamsOutput'
          - description: Identifies a Kinesis data stream as the destination.
        KinesisFirehoseOutput:
          allOf:
          - $ref: '#/components/schemas/KinesisFirehoseOutput'
          - description: Identifies a Kinesis Data Firehose delivery stream as the destination.
        LambdaOutput:
          allOf:
          - $ref: '#/components/schemas/LambdaOutput'
          - description: Identifies an Amazon Lambda function as the destination.
        DestinationSchema:
          allOf:
          - $ref: '#/components/schemas/DestinationSchema'
          - description: 'Describes the data format when records are written to the destination. '
      description: <p> Describes a SQL-based Kinesis Data Analytics application's output configuration, in which you identify an in-application stream and a destination where you want the in-application stream data to be written. The destination can be a Kinesis data stream or a Kinesis Data Firehose delivery stream. </p> <p/>
    KinesisStreamsOutputDescription:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The Amazon Resource Name (ARN) of the Kinesis data stream.
        RoleARN:
          allOf:
          - $ref: '#/components/schemas/RoleARN'
          - description: <p>The ARN of the IAM role that Kinesis Data Analytics can assume to access the stream.</p> <note> <p>Provided for backward compatibility. Applications that are created with the current API version have an application-level service execution role rather than a resource-level role.</p> </note>
      description: 'For an SQL-based Kinesis Data Analytics application''s output, describes the Kinesis data stream that is configured as its destination. '
    OutputDescriptions:
      type: array
      items:
        $ref: '#/components/schemas/OutputDescription'
    Id:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 50
    ResourceNotFoundException: {}
    ResourceInUseException: {}
    KinesisFirehoseOutput:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The ARN of the destination delivery stream to write to.
      description: 'For a SQL-based Kinesis Data Analytics application, when configuring application output, identifies a Kinesis Data Firehose delivery stream as the destination. You provide the stream Amazon Resource Name (ARN) of the delivery stream. '
    RecordFormatType:
      type: string
      enum:
      - JSON
      - CSV
    InAppStreamName:
      type: string
      pattern: '[^-\s<>&]*'
      minLength: 1
      maxLength: 32
    InvalidRequestException: {}
    KinesisStreamsOutput:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The ARN of the destination Kinesis data stream to write to.
      description: 'When you configure a SQL-based Kinesis Data Analytics application''s output, identifies a Kinesis data stream as the destination. You provide the stream Amazon Resource Name (ARN). '
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/firehose/
x-hasEquivalentPaths: true
