openapi: 3.0.0
info:
  version: 2015-08-04
  x-release: v4
  title: 'Amazon Kinesis Firehose CreateSignalingChannel #X Amz Target=KinesisAnalytics 20180523.AddApplicationInputProcessingConfiguration API'
  description: <fullname>Amazon Kinesis Data Firehose API Reference</fullname> <p>Amazon Kinesis Data Firehose is a fully managed service that delivers real-time streaming data to destinations such as Amazon Simple Storage Service (Amazon S3), Amazon OpenSearch Service, Amazon Redshift, Splunk, and various other supportd destinations.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: firehose
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/firehose-2015-08-04.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://firehose.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Firehose multi-region endpoint
- url: https://firehose.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Firehose multi-region endpoint
- url: http://firehose.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Firehose endpoint for China (Beijing) and China (Ningxia)
- url: https://firehose.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Firehose endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=KinesisAnalytics 20180523.AddApplicationInputProcessingConfiguration'
paths:
  /#X-Amz-Target=KinesisAnalytics_20180523.AddApplicationInputProcessingConfiguration:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: AddApplicationInputProcessingConfiguration
      description: Adds an <a>InputProcessingConfiguration</a> to a SQL-based Kinesis Data Analytics application. An input processor pre-processes records on the input stream before the application's SQL code executes. Currently, the only input processor available is <a href="https://docs.aws.amazon.com/lambda/">Amazon Lambda</a>.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddApplicationInputProcessingConfigurationResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: ResourceInUseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceInUseException'
        '482':
          description: InvalidArgumentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArgumentException'
        '483':
          description: ConcurrentModificationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentModificationException'
        '484':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddApplicationInputProcessingConfigurationRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - KinesisAnalytics_20180523.AddApplicationInputProcessingConfiguration
      tags:
      - '#X Amz Target=KinesisAnalytics 20180523.AddApplicationInputProcessingConfiguration'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    ApplicationName:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 128
    ApplicationVersionId:
      type: integer
      minimum: 1
      maximum: 999999999
    AddApplicationInputProcessingConfigurationRequest:
      type: object
      required:
      - ApplicationName
      - CurrentApplicationVersionId
      - InputId
      - InputProcessingConfiguration
      title: AddApplicationInputProcessingConfigurationRequest
      properties:
        ApplicationName:
          allOf:
          - $ref: '#/components/schemas/ApplicationName'
          - description: The name of the application to which you want to add the input processing configuration.
        CurrentApplicationVersionId:
          allOf:
          - $ref: '#/components/schemas/ApplicationVersionId'
          - description: The version of the application to which you want to add the input processing configuration. You can use the <a>DescribeApplication</a> operation to get the current application version. If the version specified is not the current version, the <code>ConcurrentModificationException</code> is returned.
        InputId:
          allOf:
          - $ref: '#/components/schemas/Id'
          - description: The ID of the input configuration to add the input processing configuration to. You can get a list of the input IDs for an application using the <a>DescribeApplication</a> operation.
        InputProcessingConfiguration:
          allOf:
          - $ref: '#/components/schemas/InputProcessingConfiguration'
          - description: The <a>InputProcessingConfiguration</a> to add to the application.
    ResourceARN:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 2048
    InputProcessingConfigurationDescription:
      type: object
      properties:
        InputLambdaProcessorDescription:
          allOf:
          - $ref: '#/components/schemas/InputLambdaProcessorDescription'
          - description: 'Provides configuration information about the associated <a>InputLambdaProcessorDescription</a> '
      description: For a SQL-based Kinesis Data Analytics application, provides the configuration information about an input processor. Currently, the only input processor available is <a href="https://docs.aws.amazon.com/lambda/">Amazon Lambda</a>.
    RoleARN:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 2048
    ConcurrentModificationException: {}
    InvalidArgumentException: {}
    Id:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 50
    ResourceNotFoundException: {}
    InputLambdaProcessorDescription:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: '<p>The ARN of the Amazon Lambda function that is used to preprocess the records in the stream.</p> <note> <p>To specify an earlier version of the Lambda function than the latest, include the Lambda function version in the Lambda function ARN. For more information about Lambda ARNs, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda">Example ARNs: Amazon Lambda</a> </p> </note>'
        RoleARN:
          allOf:
          - $ref: '#/components/schemas/RoleARN'
          - description: <p>The ARN of the IAM role that is used to access the Amazon Lambda function.</p> <note> <p>Provided for backward compatibility. Applications that are created with the current API version have an application-level service execution role rather than a resource-level role.</p> </note>
      description: For a SQL-based Kinesis Data Analytics application, an object that contains the Amazon Resource Name (ARN) of the Amazon Lambda function that is used to preprocess records in the stream.
    InputProcessingConfiguration:
      type: object
      required:
      - InputLambdaProcessor
      properties:
        InputLambdaProcessor:
          allOf:
          - $ref: '#/components/schemas/InputLambdaProcessor'
          - description: The <a>InputLambdaProcessor</a> that is used to preprocess the records in the stream before being processed by your application code.
      description: For a SQL-based Kinesis Data Analytics application, describes a processor that is used to preprocess the records in the stream before being processed by your application code. Currently, the only input processor available is <a href="https://docs.aws.amazon.com/lambda/">Amazon Lambda</a>.
    ResourceInUseException: {}
    InvalidRequestException: {}
    AddApplicationInputProcessingConfigurationResponse:
      type: object
      properties:
        ApplicationARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: The Amazon Resource Name (ARN) of the application.
        ApplicationVersionId:
          allOf:
          - $ref: '#/components/schemas/ApplicationVersionId'
          - description: 'Provides the current application version. '
        InputId:
          allOf:
          - $ref: '#/components/schemas/Id'
          - description: The input ID that is associated with the application input. This is the ID that Kinesis Data Analytics assigns to each input configuration that you add to your application.
        InputProcessingConfigurationDescription:
          allOf:
          - $ref: '#/components/schemas/InputProcessingConfigurationDescription'
          - description: The description of the preprocessor that executes on records in this input before the application's code is run.
    InputLambdaProcessor:
      type: object
      required:
      - ResourceARN
      properties:
        ResourceARN:
          allOf:
          - $ref: '#/components/schemas/ResourceARN'
          - description: '<p>The ARN of the Amazon Lambda function that operates on records in the stream.</p> <note> <p>To specify an earlier version of the Lambda function than the latest, include the Lambda function version in the Lambda function ARN. For more information about Lambda ARNs, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda">Example ARNs: Amazon Lambda</a> </p> </note>'
      description: 'An object that contains the Amazon Resource Name (ARN) of the Amazon Lambda function that is used to preprocess records in the stream in a SQL-based Kinesis Data Analytics application. '
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/firehose/
x-hasEquivalentPaths: true
