openapi: 3.2.0
info:
  version: 2013-12-02
  x-release: v4
  title: 'Amazon Kinesis #X Amz Target=Kinesis 20131202.PutRecords API'
  description: 'Amazon Kinesis Data Streams Service API Reference

    Amazon Kinesis Data Streams is a managed service that scales elastically for real-time processing of streaming big data.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: kinesis
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/kinesis-2013-12-02.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://kinesis.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Kinesis multi-region endpoint
- url: https://kinesis.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Kinesis multi-region endpoint
- url: http://kinesis.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Kinesis endpoint for China (Beijing) and China (Ningxia)
- url: https://kinesis.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Kinesis endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=Kinesis 20131202.PutRecords'
paths:
  /#X-Amz-Target=Kinesis_20131202.PutRecords:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: PutRecords
      description: 'Writes multiple data records into a Kinesis data stream in a single call (also referred to as a PutRecords request). Use this operation to send data into the stream for data ingestion and processing.


        When invoking this API, it is recommended you use the StreamARN input parameter rather than the StreamName input parameter.


        Each PutRecords request can support up to 500 records. Each record in the request can be as large as 1 MiB, up to a limit of 5 MiB for the entire request, including partition keys. Each shard can support writes up to 1,000 records per second, up to a maximum data write total of 1 MiB per second.


        You must specify the name of the stream that captures, stores, and transports the data; and an array of request Records, with each record in the array requiring a partition key and data blob. The record size limit applies to the total size of the partition key and data blob.


        The data blob can be any type of data; for example, a segment from a log file, geographic/location data, website clickstream data, and so on.


        The partition key is used by Kinesis Data Streams as input to a hash function that maps the partition key and associated data to a specific shard. An MD5 hash function is used to map partition keys to 128-bit integer values and to map associated data records to shards. As a result of this hashing mechanism, all data records with the same partition key map to the same shard within the stream. For more information, see Adding Data to a Stream in the Amazon Kinesis Data Streams Developer Guide.


        Each record in the Records array may include an optional parameter, ExplicitHashKey, which overrides the partition key to shard mapping. This parameter allows a data producer to determine explicitly the shard where the record is stored. For more information, see Adding Multiple Records with PutRecords in the Amazon Kinesis Data Streams Developer Guide.


        The PutRecords response includes an array of response Records. Each record in the response array directly correlates with a record in the request array using natural ordering, from the top to the bottom of the request and response. The response Records array always includes the same number of records as the request array.


        The response Records array includes both successfully and unsuccessfully processed records. Kinesis Data Streams attempts to process all records in each PutRecords request. A single record failure does not stop the processing of subsequent records. As a result, PutRecords doesn''t guarantee the ordering of records. If you need to read records in the same order they are written to the stream, use PutRecord instead of PutRecords, and write to the same shard.


        A successfully processed record includes ShardId and SequenceNumber values. The ShardId parameter identifies the shard in the stream where the record is stored. The SequenceNumber parameter is an identifier assigned to the put record, unique to all records in the stream.


        An unsuccessfully processed record includes ErrorCode and ErrorMessage values. ErrorCode reflects the type of error and can be one of the following values: ProvisionedThroughputExceededException or InternalFailure. ErrorMessage provides more detailed information about the ProvisionedThroughputExceededException exception including the account ID, stream name, and shard ID of the record that was throttled. For more information about partially successful responses, see Adding Multiple Records with PutRecords in the Amazon Kinesis Data Streams Developer Guide.


        After you write a record to a stream, you cannot modify that record or its order within the stream.


        By default, data records are accessible for 24 hours from the time that they are added to a stream. You can use IncreaseStreamRetentionPeriod or DecreaseStreamRetentionPeriod to modify this retention period.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutRecordsOutput'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: InvalidArgumentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArgumentException'
        '482':
          description: ProvisionedThroughputExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvisionedThroughputExceededException'
        '483':
          description: KMSDisabledException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSDisabledException'
        '484':
          description: KMSInvalidStateException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSInvalidStateException'
        '485':
          description: KMSAccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSAccessDeniedException'
        '486':
          description: KMSNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSNotFoundException'
        '487':
          description: KMSOptInRequired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSOptInRequired'
        '488':
          description: KMSThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSThrottlingException'
        '489':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutRecordsInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - Kinesis_20131202.PutRecords
      tags:
      - '#X Amz Target=Kinesis 20131202.PutRecords'
      summary: Put records
      x-summary-source: derived
components:
  schemas:
    KMSAccessDeniedException: {}
    SequenceNumber:
      type: string
      pattern: 0|([1-9]\d{0,128})
    KMSNotFoundException: {}
    KMSThrottlingException: {}
    PutRecordsRequestEntry:
      type: object
      required:
      - Data
      - PartitionKey
      properties:
        Data:
          allOf:
          - $ref: '#/components/schemas/Data'
          - description: The data blob to put into the record, which is base64-encoded when the blob is serialized. When the data blob (the payload before base64-encoding) is added to the partition key size, the total size must not exceed the maximum record size (1 MiB).
        ExplicitHashKey:
          allOf:
          - $ref: '#/components/schemas/HashKey'
          - description: The hash value used to determine explicitly the shard that the data record is assigned to by overriding the partition key hash.
        PartitionKey:
          allOf:
          - $ref: '#/components/schemas/PartitionKey'
          - description: Determines which shard in the stream the data record is assigned to. Partition keys are Unicode strings with a maximum length limit of 256 characters for each key. Amazon Kinesis Data Streams uses the partition key as input to a hash function that maps the partition key and associated data to a specific shard. Specifically, an MD5 hash function is used to map partition keys to 128-bit integer values and to map associated data records to shards. As a result of this hashing mechanism, all data records with the same partition key map to the same shard within the stream.
      description: Represents the output for <code>PutRecords</code>.
    KMSDisabledException: {}
    ShardId:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 128
    AccessDeniedException: {}
    PutRecordsInput:
      type: object
      required:
      - Records
      title: PutRecordsInput
      properties:
        Records:
          allOf:
          - $ref: '#/components/schemas/PutRecordsRequestEntryList'
          - description: The records associated with the request.
        StreamName:
          allOf:
          - $ref: '#/components/schemas/StreamName'
          - description: The stream name associated with the request.
        StreamARN:
          allOf:
          - $ref: '#/components/schemas/StreamARN'
          - description: The ARN of the stream.
      description: A <code>PutRecords</code> request.
    KMSInvalidStateException: {}
    InvalidArgumentException: {}
    HashKey:
      type: string
      pattern: 0|([1-9]\d{0,38})
    PutRecordsOutput:
      type: object
      required:
      - Records
      properties:
        FailedRecordCount:
          allOf:
          - $ref: '#/components/schemas/PositiveIntegerObject'
          - description: The number of unsuccessfully processed records in a <code>PutRecords</code> request.
        Records:
          allOf:
          - $ref: '#/components/schemas/PutRecordsResultEntryList'
          - description: An array of successfully and unsuccessfully processed record results. A record that is successfully added to a stream includes <code>SequenceNumber</code> and <code>ShardId</code> in the result. A record that fails to be added to a stream includes <code>ErrorCode</code> and <code>ErrorMessage</code> in the result.
        EncryptionType:
          allOf:
          - $ref: '#/components/schemas/EncryptionType'
          - description: '<p>The encryption type used on the records. This parameter can be one of the following values:</p> <ul> <li> <p> <code>NONE</code>: Do not encrypt the records.</p> </li> <li> <p> <code>KMS</code>: Use server-side encryption on the records using a customer-managed Amazon Web Services KMS key.</p> </li> </ul>'
      description: ' <code>PutRecords</code> results.'
    PartitionKey:
      type: string
      minLength: 1
      maxLength: 256
    ProvisionedThroughputExceededException: {}
    EncryptionType:
      type: string
      enum:
      - NONE
      - KMS
    PutRecordsResultEntryList:
      type: array
      items:
        $ref: '#/components/schemas/PutRecordsResultEntry'
      minItems: 1
      maxItems: 500
    ResourceNotFoundException: {}
    ErrorCode:
      type: string
    KMSOptInRequired: {}
    Data:
      type: string
      minLength: 0
      maxLength: 1048576
    PutRecordsRequestEntryList:
      type: array
      items:
        $ref: '#/components/schemas/PutRecordsRequestEntry'
      minItems: 1
      maxItems: 500
    StreamName:
      type: string
      pattern: '[a-zA-Z0-9_.-]+'
      minLength: 1
      maxLength: 128
    StreamARN:
      type: string
      pattern: arn:aws.*:kinesis:.*:\d{12}:stream/\S+
      minLength: 1
      maxLength: 2048
    PositiveIntegerObject:
      type: integer
      minimum: 1
    ErrorMessage:
      type: string
    PutRecordsResultEntry:
      type: object
      properties:
        SequenceNumber:
          allOf:
          - $ref: '#/components/schemas/SequenceNumber'
          - description: The sequence number for an individual record result.
        ShardId:
          allOf:
          - $ref: '#/components/schemas/ShardId'
          - description: The shard ID for an individual record result.
        ErrorCode:
          allOf:
          - $ref: '#/components/schemas/ErrorCode'
          - description: The error code for an individual record result. <code>ErrorCodes</code> can be either <code>ProvisionedThroughputExceededException</code> or <code>InternalFailure</code>.
        ErrorMessage:
          allOf:
          - $ref: '#/components/schemas/ErrorMessage'
          - description: The error message for an individual record result. An <code>ErrorCode</code> value of <code>ProvisionedThroughputExceededException</code> has an error message that includes the account ID, stream name, and shard ID. An <code>ErrorCode</code> value of <code>InternalFailure</code> has the error message <code>"Internal Service Failure"</code>.
      description: Represents the result of an individual record from a <code>PutRecords</code> request. A record that is successfully added to a stream includes <code>SequenceNumber</code> and <code>ShardId</code> in the result. A record that fails to be added to the stream includes <code>ErrorCode</code> and <code>ErrorMessage</code> in the result.
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/kinesis/
x-hasEquivalentPaths: true
